# Generated by Django 4.1.7 on 2023-03-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoes_name', models.CharField(max_length=100)),
                ('shoes_image', models.URLField()),
                ('shoes_price', models.CharField(max_length=1000000)),
            ],
            options={
                'db_table': 'shoes',
            },
        ),
    ]
